//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartRental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelManag
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HotelManag()
        {
            this.HotelPhoto1 = new HashSet<HotelPhoto>();
            this.Order = new HashSet<Order>();
            this.UserBrowse = new HashSet<UserBrowse>();
            this.UserEvaluate = new HashSet<UserEvaluate>();
        }

       

        public int HotelID { get; set; }
        public string HotelName { get; set; }
        public string HotelCity { get; set; }
        public string AddressDetails { get; set; }
        public string HotelType { get; set; }
        public Nullable<decimal> HotelGrade { get; set; }
        public string HotelDiscount { get; set; }
        public string HotelIntro { get; set; }
        public string HotelBoss { get; set; }
        public string HotelPhone { get; set; }
        public string HotelPhoto { get; set; }
        public string HotelRule { get; set; }
        public string HotelOpentime { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<bool> HotelRatify { get; set; }
        public string HotelFacility { get; set; }
        public System.DateTime Hoteltration_time { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelPhoto> HotelPhoto1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
        public virtual RoomMessage RoomMessage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserBrowse> UserBrowse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserEvaluate> UserEvaluate { get; set; }
    }
}
