//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartRental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelManag
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HotelManag()
        {
            this.Order = new HashSet<Order>();
            this.RoomMessage = new HashSet<RoomMessage>();
            this.UserBrowse = new HashSet<UserBrowse>();
            this.UserEvaluate = new HashSet<UserEvaluate>();
            this.UserMessage = new HashSet<UserMessage>();
        }
    
        public int HotelID { get; set; }
        public string HotelName { get; set; }
        public string HotelCity { get; set; }
        public string AddressDetails { get; set; }
        public string HotelType { get; set; }
        public Nullable<decimal> HotelGrade { get; set; }
        public Nullable<decimal> HotelDiscount { get; set; }
        public string HotelIntro { get; set; }
        public string HotelBoss { get; set; }
        public Nullable<int> HotelPhotoID { get; set; }
        public string HotelRule { get; set; }
        public Nullable<System.DateTime> HotelOpentime { get; set; }
        public Nullable<bool> HotelRatify { get; set; }
        public string HotelFacility { get; set; }
        public Nullable<System.DateTime> Hoteltration_time { get; set; }
        public Nullable<int> Hotelrecommen { get; set; }
        public string HotelPhone { get; set; }
    
        public virtual HotelPhoto HotelPhoto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomMessage> RoomMessage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserBrowse> UserBrowse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserEvaluate> UserEvaluate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserMessage> UserMessage { get; set; }
    }
}
