//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartRental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mattres
    {
        public int MattresID { get; set; }
        public string MattresType { get; set; }
        public Nullable<System.DateTime> MattresTime { get; set; }
    }
}
