//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartRental.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SmartRentalSystemEntities : DbContext
    {
        public SmartRentalSystemEntities()
            : base("name=SmartRentalSystemEntities")
        {
            Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HotelManag> HotelManag { get; set; }
        public virtual DbSet<HotelPhoto> HotelPhoto { get; set; }
        public virtual DbSet<Mattres> Mattres { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<RoomMessage> RoomMessage { get; set; }
        public virtual DbSet<RoomPhoto> RoomPhoto { get; set; }
        public virtual DbSet<RoomType> RoomType { get; set; }
        public virtual DbSet<user_roles> user_roles { get; set; }
        public virtual DbSet<UserBrowse> UserBrowse { get; set; }
        public virtual DbSet<UserEvaluate> UserEvaluate { get; set; }
        public virtual DbSet<UserMessage> UserMessage { get; set; }
    }
}
