//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartRental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public int UserID { get; set; }
        public string OrderNumber { get; set; }
        public int HotelID { get; set; }
        public Nullable<int> RoomID { get; set; }
        public Nullable<System.DateTime> Ordertime { get; set; }
        public Nullable<System.DateTime> ArrivalDate { get; set; }
        public Nullable<System.DateTime> LeaveTime { get; set; }
        public Nullable<decimal> PayablePrice { get; set; }
        public Nullable<decimal> ActualPrice { get; set; }
        public string ClientPhone { get; set; }
        public string ClientName { get; set; }
        public string OrderState { get; set; }
        public string ClientId { get; set; }
    
        public virtual HotelManag HotelManag { get; set; }
        public virtual RoomMessage RoomMessage { get; set; }
        public virtual UserMessage UserMessage { get; set; }
    }
}
