//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartRental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomPhoto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoomPhoto()
        {
            this.RoomMessage = new HashSet<RoomMessage>();
        }
    
        public int RoomPhotoID { get; set; }
        public string PhotoName1 { get; set; }
        public string PhotoName2 { get; set; }
        public string PhotoName3 { get; set; }
        public string PhotoName4 { get; set; }
        public string PhotoName5 { get; set; }
        public string PhotoName6 { get; set; }
        public string PhotoName7 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomMessage> RoomMessage { get; set; }
    }
}
