//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartRental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomPhoto
    {
        public int RmPtID { get; set; }
        public Nullable<int> RoomID { get; set; }
        public string PhotoName1 { get; set; }
        public string PhotoName2 { get; set; }
        public string PhotoName3 { get; set; }
        public string PhotoName4 { get; set; }
        public string PhotoName5 { get; set; }
        public string PhotoName6 { get; set; }
        public string PhotoName7 { get; set; }
    
        public virtual RoomMessage RoomMessage { get; set; }
    }
}
