//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartRental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMessage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserMessage()
        {
            this.Order = new HashSet<Order>();
            this.UserBrowse = new HashSet<UserBrowse>();
            this.UserEvaluate = new HashSet<UserEvaluate>();
          
         
        }
    
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string UserPhone { get; set; }
        public string UserPwd { get; set; }
        public string Email { get; set; }
        public Nullable<bool> User_status { get; set; }
        public Nullable<bool> sex { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string HeadPhoto { get; set; }
        public string UserGrade { get; set; }
        public Nullable<System.DateTime> Last_landing_time { get; set; }
        public Nullable<System.DateTime> Registration_time { get; set; }
        public Nullable<int> HotelID { get; set; }
    
        public virtual HotelManag HotelManag { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserBrowse> UserBrowse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserEvaluate> UserEvaluate { get; set; }
    }
}
