//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartRental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserEvaluate
    {
        public int EvaluateID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> EvaluateTime { get; set; }
        public Nullable<System.DateTime> ArrivalDate { get; set; }
        public string RoomType { get; set; }
        public Nullable<int> HotelAssess { get; set; }
        public string HotelRemark { get; set; }
        public Nullable<int> HotelID { get; set; }
    
        public virtual HotelManag HotelManag { get; set; }
        public virtual UserMessage UserMessage { get; set; }
    }
}
