//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartRental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserBrowse
    {
        public int BrowseID { get; set; }
        public int UserID { get; set; }
        public int HotelID { get; set; }
        public int EvaluateID { get; set; }
        public int RoomID { get; set; }
        public Nullable<System.DateTime> BrowseTime { get; set; }
    
        public virtual HotelManag HotelManag { get; set; }
        public virtual RoomMessage RoomMessage { get; set; }
        public virtual UserMessage UserMessage { get; set; }
        public virtual UserMessage UserMessage1 { get; set; }
    }
}
