//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartRental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_UserBrHishory
    {
        public int BrowseID { get; set; }
        public Nullable<int> HotelID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> BrowseTime { get; set; }
        public string Hotelphoto1 { get; set; }
        public string HotelName { get; set; }
        public string HotelCity { get; set; }
        public string HotelType { get; set; }
        public Nullable<decimal> HotelGrade { get; set; }
        public string HotelPhone { get; set; }
        public Nullable<decimal> HotelDiscount { get; set; }
    }
}
