//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartRental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_HotelDateYearmoney
    {
        public System.Guid guid { get; set; }
        public string datemoneytime { get; set; }
        public Nullable<int> HotelID { get; set; }
        public Nullable<decimal> summoney { get; set; }
    }
}
